"""agentmaker.rag.types: the RAG data types.

Document: one source document (the output of a loader, the input to a splitter).
Chunk: one text chunk (the output of a splitter, and the unit used later for ingestion and retrieval).
A document is split into multiple chunks, and all chunks share the same doc_id, which makes it easy to
"delete old chunks / upsert by doc_id when a document is updated".
"""

import uuid
from dataclasses import dataclass, field
from typing import Any, Dict, List, Optional


@dataclass(frozen=True)
class ChunkingConfig:
    """Chunking knobs (used on the ingestion write path). Mirrors the splitter's _CHUNK_TOKENS/_OVERLAP_TOKENS defaults.

    Attributes:
        chunk_tokens: Target token count for a chunk.
        overlap_tokens: Overlap token count between adjacent chunks (must satisfy 0 <= overlap < chunk).
    """
    chunk_tokens: int = 512
    overlap_tokens: int = 64

    def validate(self) -> None:
        """Range check: chunk_tokens > 0 and 0 <= overlap_tokens < chunk_tokens."""
        if self.chunk_tokens <= 0 or not 0 <= self.overlap_tokens < self.chunk_tokens:
            raise ValueError(
                f"require chunk_tokens > 0 and 0 <= overlap < chunk, got chunk={self.chunk_tokens}, overlap={self.overlap_tokens}")


@dataclass(frozen=True)
class RagConfig:
    """RAG multi-query expansion knobs (used on the retrieval read path, only relevant when a query_transformer is attached).

    Attributes:
        mq_pool_factor: The multiplier for how many extra candidates to fetch per query when doing multi-query.
        mq_max_queries: The maximum fan-out count for query expansion.
    """
    mq_pool_factor: int = 2
    mq_max_queries: int = 8

    def validate(self) -> None:
        """Range check: both must be >= 1."""
        if self.mq_pool_factor < 1 or self.mq_max_queries < 1:
            raise ValueError(
                f"mq_pool_factor / mq_max_queries must be >= 1, got {self.mq_pool_factor}, {self.mq_max_queries}")


@dataclass
class Document:
    """One source document.

    Attributes:
        content: The body text (already converted by the loader into plain text / Markdown).
        doc_id: Unique document id, auto-generated by default; used for dedup / upsert.
        title: Document-level title (defaults to the file name), used as the leading prefix of each chunk's
            heading path so that "which file it belongs to" becomes part of the retrievable context.
        source: The origin (file path or name).
        format: The original format (md / json / pdf, etc.); the splitter picks its chunking strategy from this.
        metadata: Accompanying information (upload time, author, etc.).
        records: For structured data (json/csv), a list of "per-record texts" pre-split by the loader; RecordSplitter
            uses it directly, one record per chunk, without a round trip through "blank-line separated" text (which
            avoids mis-splitting records whose body contains blank lines / CSV multi-line cells). For unstructured
            or hand-constructed documents this is None, and RecordSplitter falls back to splitting on blank lines.
    """
    content: str
    doc_id: str = field(default_factory=lambda: uuid.uuid4().hex)
    title: str = ""
    source: str = ""
    format: str = ""
    metadata: Dict[str, Any] = field(default_factory=dict)
    records: Optional[List[str]] = None


@dataclass
class Chunk:
    """One text chunk.

    Attributes:
        content: The chunk body text.
        chunk_id: Unique chunk id, auto-generated by default.
        doc_id: The doc_id of the owning document (for tracing back / deleting by document).
        heading_path: The heading path, e.g. "Chapter 1 > 1.1 Introduction" (only present for Markdown chunking).
        index: The position within the document (0-based).
        metadata: Accompanying information (source, format, etc.), useful for tracing provenance after retrieval.
    """
    content: str
    chunk_id: str = field(default_factory=lambda: uuid.uuid4().hex)
    doc_id: str = ""
    heading_path: str = ""
    index: int = 0
    metadata: Dict[str, Any] = field(default_factory=dict)

    def __str__(self) -> str:
        """Make print(chunk) show "[heading_path] body (truncated)" for easier debugging."""
        text = self.content if len(self.content) <= 50 else self.content[:50] + "…"
        head = f"[{self.heading_path}] " if self.heading_path else ""
        return f"{head}{text}"


@dataclass(frozen=True)
class IngestReport:
    """The result of one ingestion (returned by IngestionPipeline.ingest_file / ingest_text).

    Attributes:
        doc_id: The doc_id of the ingested document (used for dedup / deleting by document).
        chunks: The number of chunks ingested (or already present when short-circuited).
        skipped: True means the content fingerprint was unchanged and the whole document was short-circuited
            (chunking / embedding / LLM enhancement were all skipped).
    """
    doc_id: str
    chunks: int
    skipped: bool = False


@dataclass(frozen=True)
class SourceRef:
    """One source of a RAG answer (the number n corresponds to the [n] citation in the answer body).

    Attributes:
        n: The source number (1-based).
        content: The original chunk content of this source.
        heading_path: The chunk's heading path (only present for Markdown chunking).
        doc_id: The doc_id of the owning document.
    """
    n: int
    content: str
    heading_path: str = ""
    doc_id: str = ""


@dataclass(frozen=True)
class AskResult:
    """RAG question-answering result (returned by RagRetriever.ask): answer text + list of sources.

    Attributes:
        answer: The answer text the model produced based on the retrieved material.
        sources: list[SourceRef], the sources the answer relies on; [] when there are no hits / no chunks relied upon.
    """
    answer: str
    sources: list
