"""agentmaker.memory.types: the data type for a single memory."""

import uuid
from dataclasses import dataclass, field
from datetime import datetime

from ..core.clock import ensure_utc, now_utc
from typing import Any, Dict, Optional

# Anchor options for recency scoring: created_at (creation time; update also refreshes updated_at, which takes effect)
# or last_accessed (refreshed whenever a retrieval hits the memory; the original Generative Agents semantics of
# "a memory that gets used stays fresh").
_RECENCY_ANCHORS = ("created_at", "last_accessed")


@dataclass(frozen=True)
class MemoryConfig:
    """All tunable knobs for the memory subsystem: combined scoring + summary + rebuild + write-time dedup + forget/write defaults. Fully frozen.

    Attributes:
        relevance_weight / recency_weight / importance_weight: the three scoring weights for search (all 0 degenerates to pure relevance).
        recency_halflife_hours: recency half-life in hours; smaller values favor newer memories more strongly.
        recency_anchor: the time anchor for the recency dimension. "created_at" (default; actually uses updated_at or
            created_at, so edited content decays by its edit time) or "last_accessed" (decays by the most recent
            retrieval-hit time, the original Generative Agents semantics).
        summary_top_k: how many memories summary takes by default.
        rebuild_batch_size: how many memories rebuild_index writes per batch.
        similar_k: how many similar memories SmartWriter looks up before writing, for dedup.
        forget_threshold: the importance threshold for Memory.forget.
        default_importance: the default used by Memory.add when importance is not given.
    """
    relevance_weight: float = 1.0
    recency_weight: float = 1.0
    importance_weight: float = 1.0
    recency_halflife_hours: float = 72.0
    recency_anchor: str = "created_at"
    search_top_k: int = 5
    summary_top_k: int = 20
    rebuild_batch_size: int = 256
    similar_k: int = 5
    forget_threshold: float = 0.3
    default_importance: float = 0.5

    def validate(self) -> None:
        """Range-check: weights non-negative, half-life > 0, count fields >= 1, threshold/importance in [0,1], anchor within the enum."""
        if min(self.relevance_weight, self.recency_weight, self.importance_weight) < 0:
            raise ValueError("scoring weights must be non-negative (relevance / recency / importance)")
        if self.recency_halflife_hours <= 0:
            raise ValueError(f"recency_halflife_hours must be > 0, got {self.recency_halflife_hours}")
        if self.recency_anchor not in _RECENCY_ANCHORS:
            raise ValueError(f"recency_anchor must be one of {_RECENCY_ANCHORS}, got {self.recency_anchor!r}")
        if self.search_top_k < 1 or self.summary_top_k < 1 or self.rebuild_batch_size < 1 or self.similar_k < 1:
            raise ValueError("search_top_k / summary_top_k / rebuild_batch_size / similar_k must be >= 1")
        if not 0 <= self.forget_threshold <= 1 or not 0 <= self.default_importance <= 1:
            raise ValueError("forget_threshold / default_importance must be within [0, 1]")


@dataclass
class MemoryItem:
    """A single memory.

    Attributes:
        content: the memory body.
        id: unique identifier, auto-generated by default (uuid).
        type: memory type (working / episodic / semantic / procedural); not enforced initially, used as a label for now.
        importance: importance in 0~1, for future importance-based eviction ("forgetting").
        created_at: the time the memory was recorded, defaults to now.
        updated_at: the time of the most recent content update; None means never updated (falls back to created_at).
            Recency scoring uses this, so edited memories decay by their edit time, fixing the case where content
            changed but the recency score still used the old time.
        last_accessed_at: the most recent retrieval-hit time; None means never hit. Used as the recency anchor when
            recency_anchor="last_accessed".
        invalid_at: soft-invalidation time; None means valid. An invalidated memory is removed from the index and no
            longer retrievable, but the source-of-truth record is kept for auditing: state changes like "the user moved
            from Shanghai to Beijing" no longer physically erase the old fact (physical deletion is reserved for forget
            / compliance cases).
        superseded_by: the id of the newer memory that supersedes this one (recorded on soft-invalidation, forming a fact
            evolution chain); None means none.
        metadata: attached information, defaults to an empty dict.
    """
    content: str
    id: str = field(default_factory=lambda: uuid.uuid4().hex)
    type: str = "semantic"
    importance: float = 0.5
    created_at: datetime = field(default_factory=now_utc)
    updated_at: Optional[datetime] = None
    last_accessed_at: Optional[datetime] = None
    invalid_at: Optional[datetime] = None
    superseded_by: Optional[str] = None
    metadata: Dict[str, Any] = field(default_factory=dict)

    def __post_init__(self) -> None:
        """Normalize all four time fields to aware UTC in one place: regardless of whether the caller or a read-back
        from an old database passes naive or aware datetimes, internally everything is aware. This avoids a TypeError
        when subtracting a naive time from an aware now in recency / invalidation scoring (see agentmaker.core.clock)."""
        self.created_at = ensure_utc(self.created_at)
        self.updated_at = ensure_utc(self.updated_at)
        self.last_accessed_at = ensure_utc(self.last_accessed_at)
        self.invalid_at = ensure_utc(self.invalid_at)

    def __str__(self) -> str:
        """Make print(item) show "[type] body (truncated if long)" for easier debugging.

        Returns:
            str: e.g. "[semantic] I'm allergic to peanuts and can't eat nuts".
        """
        text = self.content if len(self.content) <= 40 else self.content[:40] + "…"
        return f"[{self.type}] {text}"
